"""Add eleitores table

Revision ID: add_eleitores_table
Revises: 
Create Date: 2025-08-11 13:55:20.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_eleitores_table'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eleitores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('titulo_eleitor', sa.String(length=12), nullable=False),
    sa.Column('zona_eleitoral', sa.String(length=10), nullable=False),
    sa.Column('secao_eleitoral', sa.String(length=10), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('data_cadastro', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('titulo_eleitor')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eleitores')
    # ### end Alembic commands ###
